from data.prompt_templates import template_prompt_1
from data.db_data_short import db_summary
from business_logic.models.llm_models import askMistral, ask_sql_coder

prompt1 = "Retrieve the names of all users who have placed an order containing more than 2 units of the product with product_id = 5."
prompt2 = "Find the total revenue generated by each user from all their orders, and display the user's first and last names along with the total revenue, ordered by the highest revenue first."
prompt3 = "List the top 3 most expensive products ordered by users in 2025, including the product name, price, and the total number of units sold for each product."
prompt4 = "Update the price of all products in the 'products' table by increasing it by 10%, but only for products that have been ordered more than 50 times."
prompt5 = "Delete all orders placed before 2020, along with their corresponding entries in the 'orders_content' table.""Delete all orders placed before 2020, along with their corresponding entries in the 'orders_content' table."

prompts = [prompt1, prompt2, prompt3, prompt4, prompt5]
#
# for idx, prompt in enumerate(prompts):
#     print(f"Prompt {idx + 1}: ")
#     formatted_prompt = template_prompt_1.format(initial_prompt=prompt, db_info=db_summary, suggested_fix="")
#     # print("Mistral")
#     # print(askMistral(formatted_prompt))
#     print("-------------------------------------------------------------")
#     print("SQL Coder")
#     ask_sql_coder(formatted_prompt)
#
print(askMistral("Generate a query to verify if a user Todor Ioan exists in a table users"))